# Generated by Django 3.0.2 on 2020-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20200426_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prob_level',
            field=models.CharField(default='', max_length=1),
        ),
    ]
